version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dbsoftware-triagem
    environment:
      POSTGRES_DB: dbtriagem
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # passar para compose depois
  # docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:25.0.4 start-dev


volumes:
  db_data:

